version: "3.7"

services:
  app:
    container_name: blog-app
    build: docker/php
    volumes:
      - ./:/app/yii
    depends_on:
      - db

  nginx:
    container_name: blog_nginx_1
    image: nginx:1.12-alpine
    ports:
      - 80:80
    volumes:
      - ./:/app/yii
      - ./docker/nginx/vhost_single_domain.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app

  db:
    image: mariadb:5.5.60
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: siteblog
      MYSQL_USER: ysk_dbu
      MYSQL_PASSWORD: ysk_pass

  redis:
    container_name: yii_redis_1
    image: redis:alpine

#  selenium-chrome:
#    container_name: p24_selenium_1
#    image: selenium/standalone-chrome:latest
#    volumes:
#      - /dev/shm:/dev/shm
#    expose:
#      - "4444"
#    ports:
#      - 4444:4444
#    environment:
#      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
#      - START_XVFB=false
#      - NODE_MAX_INSTANCES=5
#      - NODE_MAX_SESSION=5
#    depends_on:
#      - nginx
#      - app

networks:
  default:
    name: yii2-starter-kit_default

